### ISSUE TITLE
rasterizer bug

### ISSUE THREAD

**Issue by brunntho** [GameTechDev/MaskedOcclusionCulling#16]
rasterizer code seems to have a bug.

Steps to reproduce:
Render two boxes into the depth buffer and write the result into a bitmap file. 
Odd artefacts arise at triangle edges. See attached image. 

![moc_bug](https://user-images.githubusercontent.com/1578727/52776412-cead9280-3041-11e9-9769-e73aa1d573a4.png)

**Comment by Hasselgren** [comment]
Hi brunntho,

This behaviour is by design. The algorithm is approximate (but conservative) in that it may incorrectly report an occluded object as visible, but never incorrectly report a visible object as occluded. For rendering it's typically ok to have a few false positives because they will be removed by the GPUs depth test later anyway. 

What you see is leakage due to the merging heuristic, which is unfortunate but also crucial to the performance of our rasterizer. This can happen when you have more than 2 visible surfaces in an 8x4 tile which may sometimes force the merging heuristic to push the depth value back (to guarantee conservative correctness). It typically happens where triangle edges intersect as in your image.

The merging heuristic is order dependent and you get least amount of leaking if you render your geometry in front-to-back depth order (this is also the best in terms of raw rasterization performance). The better the sorting the closer you will get to the exact solution. In practice it's usually enough to do a rough per-object sort, or a sorted traversal of your scene tree/graph structure. Landscapes and other extremely large singular objects should be split up and not sent as a single large drawcall.

Hope this helps,
Jon

**Comment by brunntho** [comment]
Hey Jon 

Thank you very much for your explanations.
