### ISSUE TITLE
Binning issues

### ISSUE THREAD

**Issue by fstrugar** [GameTechDev/MaskedOcclusionCulling#5]
I think there's two small issues with triangle binning:

1.) In BinTriangles, binWidth/binHeight are rounded down to multiple of TILE_WIDTH/TILE_HEIGHT but then the binning code does not account for the lowest/rightmost row/column potentially being smaller than the resolution, thus missing some triangles. Rounding up instead seems to be ok (but CullingThreadpool::SetupScissors needs to be updated accordingly).

2.) The CullingThreadpool::SetupScissors uses fixed values of BIN_WIDTH_CLAMP/BIN_HEIGHT_CLAMP which should actually be current implementation's TILE_WIDTH/TILE_HEIGHT. Since these are not tweakable anyway, it probably doesn't really matter, but it'd be nice to simply get them from the connected MaskedOcclusionCulling instance directly just to future proof.

**Comment by Hasselgren** [comment]
Hi Filip,

1.) I don't think this is an issue. The binning code has been run on some pretty complex scenes and I've not noticed any dropouts. It actually works the opposite way from what you wrote. The binWidth/Height values are rounded down, so it's the bottom/rightmost bins that are larger than the regular tile size. If you look at how startXY/endXY bin coordinates are computed (MaskedOcclusionCullingCommon.inl:1684-1687), the result of `x / binWidth` will be in the range `[0, nBinsW+1]` which is then clamped to `[0, nBinsW]`. Instead of having `(nBinsW + 1)*(nBinsH + 1)` bins, with smaller bins at the right/bottom borders, we went will having `nBinsW*nBinsH` bins and larger bins at the borders instead.

This is mirrored in CullingThreadpool.cpp:237-240, which computes larger scissor rectangles for the last bins in the x/y directions.

`mRects[threadIdx].mMaxX = tx + 1 == mBinsW ? width : (tx + 1) * binWidth;`
`mRects[threadIdx].mMaxY = ty + 1 == mBinsH ? height : (ty + 1) * binHeight;`

2.) This is a valid point. The binning / scissoring is the part of the code I'm most dissatisfied with. A general problem is that the binning code assumes that scissor boxes are computed in a very specific way, or it will not work (see the whole discussion on 1 above). It's not very clear from the code, and could be a source of bugs. 

I think the BIN_WIDTH_CLAMP/BIN_HEIGHT_CLAMP was just introduced to not create a dependency between CullingThreadpool.cpp and the other files. The way I see it, the CullingThreadpool files are just an example of how you can do threading, but not really part of the core library, so I didn't want to introduce any dependencies.

I think it would make sense to introduce a function in the MaskedOcclusionCulling class to compute the ScissorRect for a specific (or all) bins. This would also make it easier to further develop the library. Currently:

`BIN_WIDTH_CLAMP = 32` 
`BIN_HEIGHT_CLAMP = 8`

where BIN_WIDTH_CLAMP is constrained by the number of bits in a SIMD element (int32) and BIN_HEIGHT_CLAMP is constrained by the number of SIMD lanes. There are only SSE and AVX versions of the algorithm at the moment. However, if you want to add AVX-512 support it would change to 16, and can potentially break code written for the current version of the library. Adding a library function to compute the scissor rectangle of a particular bin could make this more safe/flexible.

/Jon

**Comment by fstrugar** [comment]
With regards to 1.), had a longer offline chat with Jon (so I could send the bug example images) - the problem was in the "for" loops, here's his answer and advice, just for the record:

> It does make sense that a triangle entirely in the "remainder part" of the odd-sized bins would not 
> trigger the loop.  I'd say the bug is on lines 1684 & 85, which should instead clamp the coordinate 
> to the last bin, and not one bin past the last one (nBinsW-1 because it's base 0 index). 
>  
> int startX = min(nBinsW - 1, bbPixelMinX.mw_i32[triIdx] / binWidth);
> int startY = min(nBinsH - 1, bbPixelMinY.mw_i32[triIdx] / binHeight);

Which should work ok in all cases (by this point, the off-screen triangles are culled out). So I'll test this out and commit a fix if everything is ok in a couple of days!

**Comment by fstrugar** [comment]
Fixed in 1c3d9d62a030f0525a932eaa8df99dab2e06b054 and 365ff940cbfeffd13f40a44cb78e0f6d1275a450.
